/**
* MIT License
*
* Copyright (c) 2019 Paweł Majewski
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the 'Software'), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/

const jokes = [
 'A kid decided to burn his house down. His dad watched, tears in his eyes. He put his arm around the mom and said, “That’s arson.”',
'Today I decided to go visit my childhood home. I asked the residents if I could come inside because I was feeling nostalgic, but they refused and slammed the door on my face. My parents are the worst.',
'“What’s your name, son?” The principal asked his student. The kid replied, “D-d-d-dav-dav-david, sir.” “Do you have a stutter?” the principal asked. The student answered, “No sir, my dad has a stutter but the guy who registered my name was a real jerk.”',
'Concerned that his son was spending too much time on video games, a dad told him, “When Abe Lincoln was your age, he was studying books by the light of the fireplace.” “Oh yeah?” the son retorts. “Well, when Abe Lincoln was your age, he was President of the United States.”',
'A father tells his son that he was adopted. “I want to meet my biological parents,” the son demands. “We are your biological parents,” the father responds. “Now pack up, the new ones will pick you up in twenty minutes.”',
'A son tells his father, “I have an imaginary girlfriend.” The father sighs and says, “You know, you could do better.” “Thanks Dad,” the son says. “That means a lot.” The father shakes his head and goes, “I was talking to your girlfriend.”',
'Yesterday, I was washing the car with my son. He said, “Dad, can’t you just use a sponge?”',
'My dad died because he couldn’t remember his blood type. He kept insisting we “be positive,” but it’s just so hard without him.',
'I tried to explain to my 4-year-old son that it’s perfectly normal to accidentally poop your pants. But he’s still making fun of me.',
'I wasn’t close to my father when he died. Which is lucky because he stepped on a landmine.',
'My wife and I have decided not to have kids. The kids are taking it pretty badly.',
'When does a joke become a dad joke? When it becomes apparent.',
'My daughter just shrieked at me, “Daaaaaad, you haven’t listened to a word I’ve said, have you?” What an odd way to begin a conversation.',
'I have a great joke about nepotism. But I’ll only tell it to my kids.',
'“Dad, can you explain to me what a solar eclipse is?” No sun.',
'What happened when the ten-year-old cannibal spilled his soup? His mother gave him an earful.',
'I’d like to have kids one day. I don’t think I could stand them any longer than that, though.',
'What did the buffalo say to his son when he dropped him off at school? Bison.',
'I wonder what my parents did to fight boredom before the internet. I asked my eighteen brothers and sisters but they didn’t have any idea either.',
'My parents raised me as an only child. Which really annoyed my younger brother.',
'I tell dad jokes but I have no kids. I’m a faux pa!',
'I bought Spotify premium for an uninterrupted music experience. But I still hear my wife’s bickering between songs.',
'I can always tell when my wife is lying just by looking at her. I can also tell when she’s standing.',
'My wife told me that I twist everything she says to my advantage. I take that as a compliment.',
'My ex and I had a very amicable divorce. I know this because when I posted on Facebook, “I’m getting a divorce,” she was the first one to like it.',
'My wife told me to quit doing my terrible Arnold impression, but don\'t worry, I\'ll return.',
'“Just look at that couple down the road,” a wife told her husband. “He keeps holding her hand, kissing her, holding the door for her. Why can’t you do that?” “Are you insane?” he responded. “I barely know the woman!”',
'I was sitting on the back porch with my wife when I suddenly blurted out, “I love you.” “Is that you or the beer talking?” she asked. I answered, “It’s me… talking to my beer.”',
'“Siri,” I asked my phone, “why am I so bad with women?" She responded, “I’m Bixby, you moron.”',
'My wife and I were out to dinner and the waitress started flirting with me. "She obviously has COVID," my wife said. "Why?" I asked. "Because she has no taste."',
'Marriage involves three rings: The engagement ring, the wedding ring, and the suffer-ring.',
'"Your wife and daughter look like twins," my friend said. "Well," I replied, "they were separated at birth."',
'One friend complained to another, “All my husband and I do anymore is fight. I\'ve been so upset, I’ve lost 20 pounds.” “If it’s that bad, why don’t you just leave him?” asked the second friend. “I’d like to lose another fifteen pounds first.”',
'My wife left a note on the fridge that said, “This isn\'t working.” I’m not sure what she’s talking about. I opened the fridge door and it’s working fine!',
'My wife wanted to spice up our sex life, so she asked if we could play doctor tonight. It seemed like a weird idea, but I’m eager to please.',
'My wife told me she didn\'t understand cloning. I told her, "That makes two of us."',
'My wife told me she’ll slam my head on the keyboard if I don\'t get off the computer. I’m not too worried, I think she’s jokinlkjhfakljn m,.nbziyoao78yv87dfaoyuofaytdf',
'My wife gave birth three times and still fits in her prom dress from high school. I gave birth zero times and I don’t fit in my pants from March.',
'When I see the names of lovers engraved on a tree, I don’t find it cute or romantic. I find it weird how many people take knives with them on dates.',
'After dinner my wife asked if I could clear the table. I needed a running start, but I made it.',
'Why didn’t the astronaut come home to his wife? He needed his space.',
'My wife gave me an ultimatum: Her or my addiction to sweets. The decision was a piece of cake.',
'I think my wife is putting glue on my antique guns collection. She denies it but I\'m sticking to my guns.',
'What’s worse than biting into an apple and finding a worm? Biting into an apple and finding half a worm.',
'I just got my doctor\'s test results and I’m really upset. Turns out, I’m not gonna be a doctor.',
'My friend said that if he went off a cliff, it would be on his own accord. It’s a good thing he drives a Civic.',
'In my free time, I like to help blind people. Verb, not adjective.',
'A doctor walks into a room with a dying patient and tells him, “I’m sorry, but you only have ten left.” The patient asks him, “Ten what, Doc? Hours? Days? Weeks?” The doctor calmly looks at him and says, “Nine.”',
'I like to spend my weekends playing chess with elderly men in the park. But it’s becoming more difficult. You try finding exactly32 old guys.',
'What do you call bears with no ears? B.',
'What’s the difference between a wizard who raises the undead and a sexy vampire? One is a necromancer and the other is a neck romancer.',
'A man walks into a magic forest and tries to cut down a talking tree. “You can\'t cut me down,” the tree complains. “I’m a talking tree!” The man responds, “You may be a talking tree, but you will dialogue.”',
'I heard Sony’s coming out with a new console during the pandemic...It’s called the Plaguestation 5.',
'When my uncle Frank died, he wanted his remains to be buried in his favorite beer mug. His last wish was to be Frank in Stein.',
'A man walks into a bar. The bartender asks, "What do you want?" The man says, "Oh, just some fruit punch." The bartender sighs and shakes his head, "If you want punch, you\'re gonna have to wait in line." The man looks around, but there is no punchline.',
'Give a man a plane ticket and he flies for the day. Push him out of the plane at 3,000 feet and he’ll fly for the rest of his life.',
'As I get older, I remember all the people I lost along the way. Maybe a career as a tour guide was not the right choice.',
'I was reading a great book about an immortal dog the other day. It was impossible to put down.',
'What do you call someone who refuses to fart in public? A private tutor.',
'I just read that someone in London gets stabbed every 52 seconds. Poor bastard.',
'They say that breakfast is the most important meal of the day. Well, not if it’s poisoned. Then the antidote becomes the most important.',
'The guy who stole my diary just died. My thoughts are with his family.',
'Do you know the last thing my grandfather said to me before he kicked the bucket? “Grandson, watch how far I can kick this bucket.”',
'If you donate a kidney, everybody loves you and you’re a total hero. But try donating five kidneys and suddenly everyone is yelling and the police get called.',
'I have a fish that can breakdance. Only for ten seconds though, and only once.',
'My grief counselor died the other day. He was so good at his job, I don’t even care.',
'I went to a smoke shop only to discover it’d been replaced by an apparel store.',
'Clothes, but no cigar.',
'Why should you never brush your teeth with your left hand? Because a toothbrush works better.',
'I used to be addicted to soap, but I’m clean now.',
'I wanted my kids to watch the orchestra, but I had to turn it off—too much sax and violins.',
'A cop started crying while he was writing me a ticket. I asked him why and he said, "It\'s a moving violation."',
'Swords will never go obsolete. They\'re cutting edge technology.',
'I asked the IT guy, "How do you make a Motherboard?" He said, "I tell her about my job."',
'What do you call it when James Bond takes a bath? Bubble 07.',
'30 percent of pet owners let their pets sleep in their bed. I tried it and my goldfish died.',
'What is the difference between a literalist and a kleptomaniac?',
'I just found out Albert Einstein existed. My whole life I thought he was a theoretical physicist.A comma. A literalist takes everything literally. A kleptomaniac takes everything, literally.',
'You used to be able to get air for free at gas stations, but now it\'s a $1. That\'s inflation for you.',
'My dad was born a conjoined twin, but separated at birth. So I have an uncle, once removed.',
'Why is it a bad idea to eat a clock? Because it\'s so time-consuming.',
'At the job interview, they asked me, “Where do you see yourself in five years?”',
'I told him, “I think we’ll still be using mirrors in five years.”',
'A buddy asked how many fish I caught. I told him it’s not polite to fish and tell.',
'How many clickbait articles does it take to change a lightbulb? The answer will shock you!',
'How do you make a water bed bouncier? Add spring water.',
'I always knock on the fridge door before opening it, just in case there\'s a salad dressing.',
'Where do dads store their dad jokes? In the dad-a-base.',
'What kind of fruit do ghosts like? Boo-berries.',
'I tried to start a professional hide and seek team, but it didn\'t work out. Turns out, good players are hard to find.',
'Women should not have children after 36—really, 36 children is enough.',
'What happens when frogs park illegally? They get toad.',
'Lance isn\'t that common a name these days, but in medieval times, they were called lance-a-lot.',
'I had an appointment to see my psychic next week, but she just called to cancel.',
'She said I won’t be able to make it.',
'“Just say NO to drugs!” Well, if I’m talking to drugs, I probably already said yes.',
'I once saw a one-handed man in a second-hand store. I told him, “I don’t think they have what you’re looking for, sir.”',
'What do you call a sad cup of coffee? Depresso.',
'What did one monocle say to the other monocle? Let\'s get together and make a spectacle of ourselves.',
'How come the Hulk doesn\'t lose his pants when he transforms? The experiment altered his jeans.',
'I didn\'t want to believe that my dad was stealing from his job as a traffic cop, but when I got home, all the signs were there.',
'I just spent $300 on a limo and learned it doesn\'t come with a driver. I can\'t believe I have nothing to chauffer it.',
'What’s green and has wheels? Grass. I lied about the wheels.',
'I have a joke about trickle down economics. But 99% of you will never get it.',
'Just got back from a job interview where I was asked if I could perform under pressure. I said I wasn’t too sure about that but I could do a wicked “Bohemian Rhapsody.”',
'What’s the best thing about living in Switzerland? I don’t know, but the flag is a big plus.',
'What has five toes and isn\'t your foot? My foot.',
'My friend claims he glued himself to his autobiography. I don\'t believe him, but that\'s his story and he\'s sticking to it.',
'When I was a kid, my mother told me I could be anyone I wanted to be. Turns out, identity theft is a crime.',
'What\'s brown and sticky? A stick.',
'My doctor told me I was going deaf. The news was hard for me to hear.',
'A century ago, two brothers decided it was possible to fly. And as you can see, they were Wright.',
'I\'m reading a horror story in braille. Something bad is going to happen, I can just feel it.',
'Anyone looking to buy a Delorean? Good shape, good mileage. Only driven from time to time.',
'During my calculus test, I had to sit between identical twins. It was hard to differentiate between them.',
'Does anybody know where a guy can find a person to hang out with, talk to, and enjoy spending time with? I\'m just asking for a friend.',
'Why did the Invisible Man turn down a job offer? He couldn’t see himself doing it.',
'When I die, I want to be cremated. It’s my last chance to have a smokin’ hot body.',
'I\'m Buzz Aldrin, second man to step on the moon. Neil before me.',
'Why was 2019 afraid of 2020? Because they had a fight and 2021.',
'Did you hear Bruce Springsteen changed the lyrics to one of his songs? What’s he going to change next—his hair? His clothes? His face?',
'This year’s Fibonacci convention is going to be really special. Apparently it’s as big as the last two put together.',
'An apple a day keeps the doctor away. At least it does if you throw it hard enough.',
'I’m addicted to collecting vintage Beatles albums. I need Help.',
'In 2017 I didn\'t do a marathon. I didn\'t do one in 2018, 2019, or 2020, either. This is a running joke.',
'Not to brag but I made six figures last year. I was also named worst employee at the toy factory.',
'Ever since we started quarantining, I\'ve only been telling inside jokes.',
'If you\'re feeling depressed, try drinking a gallon of water before you go to sleep. It\'ll give you a reason to get out of bed in the morning.',
'My landlord told me we need to talk about the heating bill. "Sure," I said. "My door is always open."',
'I built a model of Mount Everest and my son asked if it was to scale. "No," I said. "It\'s to look at."',
'What’s an astronaut’s favorite part of the computer? The Space Bar.',
'I was playing chess with my friend and he said, “Let’s make this interesting.” So we stopped playing chess.',
'I was in a job interview the other day and they asked if I could perform under pressure. I said no, but I could perform Bohemian Rhapsody.',
'Why didn\'t the vampire attack Taylor Swift? She had bad blood.',
'Today I’m attaching a light to the ceiling, but I’m afraid I’ll probably screw it up.',
'I hate it when people say age is only a number. Age is clearly a word.',
'I can\'t take my dog to the pond anymore because the ducks keep attacking him. That\'s what I get for buying a pure bread dog.',
'Someone complimented my parking today! They left a sweet note on my windshield that said “parking fine.”',
'I was excited to hear Apple might start selling its own cars until I learned they wouldn’t support windows.',
'I just applied for a job down at the diner. I told them I really bring a lot to the table.',
'"Cop: I\'m arresting you for downloading the entire Wikipedia." Man: "Wait! I can explain everything!"',
'My friend couldn\'t afford to pay his bill, so I sent him a "Get Well Soon" card.',
'Why\'d the alternate universe Spider-Man do so well on his driving test? He\'s an excellent parallel Parker.',
'Never date a tennis player. Love means nothing to them.',
'What\'s a lawyer\'s favorite drink? Subpoena colada.',
'What did Yoda say when he saw himself in 4K? HDMI.',
'What do you call a wizard who\'s really bad at football? Fumbledore.',
'How do nonbinary people hurt each other? They slash them. (They/them)',
'I used to hate facial hair, but then it grew on me.',
'What\'s blue and not very heavy? Light blue.',
'I don\'t get why bakers aren\'t wealthier. They make so much dough.',
'I asked my wife if I was the only one she slept with. She said yes—the others were 7’s and 8’s.',
'How do you make a tissue dance? You put a little boogie in it.',
'How do flat-earthers travel? On a plane.',
'I ordered a chicken and an egg from Amazon. I\'ll let you know.',
'Imagine if you walked into a bar and there was a long line of people waiting to take a swing at you. That’s the punch line.',
'My wife left me because of my obsession with pasta. I\'m feeling cannelloni right now.',
'Have you heard about the restaurant on the moon? Great food, no atmosphere.',
'I don\'t trust stairs. They\'re always up to something.',
'People in Athens rarely get up before sunrise. Dawn is tough on Greece.',
'What is a guitar player\'s favorite Italian food? Strum-boli.',
'How does cereal pay its bills? With Chex.',
'I found a wooden shoe in my toilet today. It was clogged.',
'I just broke up with my mathematician girlfriend. She was obsessed with an X.',
'I can\'t take my dog to the pond anymore because the ducks keep attacking him. That\'s what I get for buying a pure bread dog.',
'To whoever stole my copy of Microsoft Office, I will find you. You have my Word.',
'What’s Forrest Gump’s password? 1forrest1.',
'I used to run a dating service for chickens. But I was struggling to make hens meet.',
'If prisoners could take their own mug shots…They’d be called cellfies.',
'Have you heard about those new corduroy pillows? They\'re making headlines.',
'If a pig loses its voice…does it become disgruntled?',
'Wanna hear a joke about paper? Never mind. It\'s tearable.',
'A panic-stricken man explained to his doctor, “You have to help me, I think I’m shrinking.” “Now settle down,” the doctor calmly told him. “You\'ll just have to learn to be a little patient.”',
'What do you call a bundle of hay in a church? Christian Bale.',
'A ship carrying red paint and a ship carrying blue paint collide in the middle of the ocean. Both crews were marooned.',
'In America, using the metric system can get you in legal trouble.',
'What do you call a line of men waiting to get haircuts? A barberqueue.',
'In fact, if you sneer at any other method of measuring liquids, you may be held in contempt of quart.',
'Who were the greenest Presidents in US history? The bushes.',
'My hotel tried to charge me ten dollars extra for air conditioning. That wasn’t cool.',
'What do you call a beehive without an exit? Unbelievable.',
'If I ever find the doctor who screwed up my limb replacement surgery…I’ll kill him with my bear hands.',
'Did you know that the first french fries weren’t cooked in France? They were cooked in Greece.',
'This morning, Siri said, “Don’t call me Shirley.” I accidentally left my phone in Airplane mode.',
'It\'s easy to convince ladies not to eat Tide Pods, but harder to deter gents.',
'I asked my date to meet me at the gym but she never showed up. I guess the two of us aren\'t going to work out.',
'How do you find Will Smith in a snowstorm? You look for fresh prints.',
'The difference between a numerator and a denominator is a short line. Only a fraction of people will understand this.',
'What do you call a Frenchman wearing sandals? Philippe Flop.',
'Why is it so cheap to throw a party at a haunted house? Because the ghosts bring all the boos.',
'I don’t get why Marvel doesn’t use the Hulk to advertise more. He’s basically one big Banner.',
'What brand of underwear do scientists wear? Kelvin Klein.',
'Which days are the strongest? Saturday and Sunday. The rest are weekdays.',
'I just found out I’m colorblind. The news came out of the purple!',
'Did you know your pupils are the last part to stop working when you die? They dilate.',
'My wife asked me the other day where I got so much candy. I said, "I always have a few Twix up my sleeve."',
'How do cows stay up to date? They read the Moo-spaper.',
'What\'s the difference between a well-dressed man on a unicycle and a poorly-dressed man on a bicycle? Attire.',
'I hate my job—all I do is crush cans all day. It’s soda pressing.',
'Where do pirates get their hooks? Second hand stores.',
'Of all the inventions of the last 100 years, the dry erase board has to be the most remarkable.',
'What does a baby computer call his father? Data.',
'After an unsuccessful harvest, why did the farmer decide to try a career in music? Because he had a ton of sick beets.',
'I only seem to get sick on weekdays. I must have a weekend immune system.',
'My friend was showing me his tool shed and pointed to a ladder. “That\'s my stepladder,” he said. "I never knew my real ladder.”',
'Certainly! Here are all the dad jokes:',
'My boss said “dress for the job you want, not for the job you have.” So I went in as Batman.',
'I went to the aquarium this weekend, but I didn’t stay long. There’s something fishy about that place.',
'What do you call a sheep who can sing and dance? Lady Ba Ba.',
'What do you call a French man wearing sandals? Philipe Fallop.',
'Why can\'t dinosaurs clap their hands? Because they\'re extinct.',
'I gave my handyman a to-do list, but he only did jobs 1, 3, and 5. Turns out he only does odd jobs.',
'Why should you never take sides in an argument at the dinner table? Trick question. It\'s the perfect time to take sides because no one\'s paying attention. Bring Tupperware.',
'Who won the neck decorating contest? It was a tie.',
'Where do rainbows go when they\'ve been bad? To prism, so they have time to reflect on what they\'ve done.',
'Dogs can\'t operate MRI machines. But catscan.',
'What do mermaids use to wash their fins? Tide.',
'What did the skillet eat on its birthday? Pan-cakes.',
'Why couldn\'t the produce manager make it to work? He could drive, but he didn\'t avocado.',
'I went to a silent auction. I won a dog whistle and two mimes.',
'How is my wallet like an onion? Every time I open it, I cry.',
'What do you call a dog who meditates? Aware wolf.',
'What kind of fish do penguins catch at night? Star fish.',
'Which vegetable has the best kung fu? Broc-lee.',
'Can a frog jump higher than a house? Of course, a house can\'t jump.',
'I was going to try an all almond diet, but that\'s just nuts.',
'I once submitted 10 puns to a joke competition. I really thought with that many, one was sure to be a winner. Sadly, no pun in ten did.',
'Why did the old man fall down the well? He couldn’t see that well.',
'I tried to make up a joke about ghosts but I couldn\'t. It had plenty of spirit but no body.',
'Dad: What is the difference between a piano, a tuna, and a pot of glue?',
'I don\'t know.',
' You can tuna piano but you can\'t piano a tuna.',
'What about the pot of glue?',
' I knew you\'d get stuck on that.',
'Two windmills were sitting on a hill. One asks the other, "Do you have a favorite song?" The other replies, "Well... all my life I have been a heavy metal fan."',
'Today at the bank, an old lady asked me to check her balance... So I pushed her over.',
'I got an A on my origami assignment when I turned my paper into my teacher.',
'How many storm troopers does it take to change a lightbulb? None, because they are all on the dark side.',
'If your house is cold, just stand in the corner. It’s always 90 degrees there.',
'Hi, I’m Cliff. Drop over sometime.',
'Did you hear about the guy who went to the doctor for a headache? The doctor examined his ear and found money. The doctor kept pulling and pulling it out until he had $1,999. Then the doctor said, "No wonder you\'re not feeling two grand!"',
'Dad, when he puts the car in reverse: "Ah, this takes me back."',
'What do you call the security guards for Samsung? Guardians of the galaxy.',
'I was making a joke about retirement. It did not work.',
'The other day I bought a thesaurus, but when I got home and opened it, all the pages were blank. I have no word to describe how angry I am.',
'The owner of the tuxedo store kept hovering over me when I was browsing, so I asked him to leave me alone. He said, “Fine, suit yourself.”',
'Why did the egg have a day off? Because it was Fryday.',
'Have you ever heard about the kidnapping at school? It\'s okay, he woke up.',
'I found a book called How to Solve 50% of Your Problems. So I bought 2.',
'Why did the coffee taste like dirt? Because it was ground just a few minutes ago.',
'Why did the Rolling Stones stop making music? Because they got to the bottom of the hill.',
'What is the best present? Broken drums! You can\'t beat them.',
'I made a song about tortilla once, now it\'s more like a wrap.',
'Did you know corduroy pillows are in style? They\'re making headlines.',
'What does a nosey pepper do? It gets jalapeño business.',
'Did you hear about the fragile myth? It was busted.',
'What word can you make shorter by adding two letters? Short.',
'What do you call a criminal landing an airplane? Condescending.',
'I stayed up all night wondering where the sun went, and then it dawned on me.',
'Why do people who live in Greece hate waking up at dawn? Because Dawn is tough on Greece.',
'How do you make holy water? You boil the hell out of it.',
'Justice is a dish best served cold. Otherwise, it\'s just water.',
'Why should you never throw grandpa\'s false teeth at a vehicle? You might denture car.',
'Why are Christmas trees bad at knitting? They always drop their needles.',
'What did the lunch box say to the refrigerator? Don\'t hate me because I\'m a little cooler.',
'What do you do to have a space party? You planet.',
'Why couldn’t the tree get on his computer? Because he could not log on.',
'What\'s a skeleton\'s favorite type of road? A dead end.',
'What did the grape say when it got stepped on? Nothing, just a little wine.',
'What did the alien say to the landscaper? Take me to your weeder.',
'Me: “I want to write when I grow up.”',
' “Why don’t you left instead?”',
'How many apples grow on an apple tree? All of them.',
'What did Elvis say to his landscaper? Thank you for the mulch!',
'Why didn\'t the lifeguard save the hippie? He was too far out!',
'What did the mother broom say to the baby broom? Time to go to sweep.',
'The other day I was attacked by a bunch of circus clowns in a parking lot. I won though, cause I went right for the juggler.',
'I\'d like to shout out sidewalks for keeping me off the streets.',
'What did the computer go to the doctor? Because he had a virus.',
'How many ears does Captain Kirk have? Three. The left ear, the right ear, and the final front-ear.',
'Did you hear about the famous pickle? He\'s a really big dill.',
'I went on Amazon to buy a lighter but all they had were 3,472 matches.',
'What do you need to make a highway in an art studio? A road map.',
'Why did the scarecrow become a successful neurosurgeon? Because he was outstanding in his field!',
'How do you organize a space party? You planet.',
'What do you call fake spaghetti? An impasta.',
'Why did the golfer bring extra pants? In case he got a hole in one.',
'Why don’t skeletons fight each other? They don’t have the guts.',
'Why did the math book look sad? Because it had too many problems.',
'How does a penguin build its house? Igloos it together.',
'Why did the bicycle fall over? It was two-tired.',
'What do you call cheese that isn\'t yours? Nacho cheese.',
'What did one wall say to the other wall? I\'ll meet you at the corner.',
'How does a scientist freshen her breath? With experi-mints.',
'What do you call a fish wearing bowtie? Sofishticated.',
'Why don’t eggs tell jokes? They’d crack each other up.',
'How do cows stay up to date with current events? They read the moos-paper.',
'Why was the math book unhappy? It had too many problems.',
'What did the zero say to the eight? Nice belt!',
'Why don\'t some couples go to the gym? Because some relationships don\'t work out.',
'How does a snowman get around? By riding an “icicle.”',
'Why don’t you ever see elephants hiding in trees? Because they’re so good at it.',
'How do you catch a squirrel? Climb a tree and act like a nut.',
'What do you call a pile of cats? A meow-tain.',
'Why did the golfer wear two pairs of pants? In case he got a hole in one.',
'What do you call a dinosaur with an extensive vocabulary? A thesaurus.',
'What did the big flower say to the little flower? “Hey, bud!”',
'Why do bees have sticky hair? Because they use honeycombs.',
'What do you get when you cross a snowman with a vampire? Frostbite.',
'How does a farmer count his cows? With a cowculator.',
'Why was the computer cold? It left its Windows open.',]

function getRandomInt(min, max) {
	min = Math.ceil(min);
	max = Math.floor(max);
	return Math.floor(Math.random() * (max - min)) + min;
}

module.exports = {
	name: 'hummus',
	aliases: ['dadjoke'],
	description: 'Returns random joke of "dad" variety commerating S49 Charity Event',
	cooldown: 5,
	execute(message) {
		const messageNumber = getRandomInt(0, jokes.length - 1);
		message.channel.send(jokes[messageNumber]);
	},
};
